---
name: Main

"on":
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.5"
      - name: Install task
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Lint
        run: task lint
      - name: Run tests
        run: task test
